### ISSUE TITLE
Error en la autenticación del usuario

### ISSUE THREAD

**Issue by MarcEngineer** [congosto/t-hoarder#14]
La herramienta ejecuta los experimentos pero no genera los outputs esperados, no realiza una descarga de tweets ni consume los recursos de la API.

En un primer momento se estructuró el expermiento como aparece en la wiki, tras su ejecución, el archivo nohup.out establecía un error de no encontrar el archivo en la carpeta "keys" correspondiente al "bearer token" tal que así:

ohup: appending output to '/home/osboxes/nohup.out'

En el archivo aparece el siguiente error:

-->File output:  /home/osboxes/Desktop//t-hoarder/store/streaming_SabadoTest.txt
Traceback (most recent call last):
  File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 462, in <module>
    main()
  File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 440, in main
    oauth=oauth_keys(app_keys_file,user_keys_file)
  File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 45, in __init__
    f = open( self.user_keys_file, 'rU')
IOError: [Errno 2] No such file or directory: '/home/osboxes/Desktop//t-hoarder/keys/AAAAAAAAAAAAAAAAAAAAAKclWAEAAAAAmxxx.key'
run command python2.7 /home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py /home/osboxes/Desktop/ SabadoTest AppMr.XX.key AAAAAAAAAAAAAAAAAAAAAKclWAEAAAAAmpUtc7xxxDSkuZ0.key --words words.txt

Ya que veo que me solicita un archivo con el nombre del Bearer token, creo un txt con el nombre del Bearer token y lo incluyo en su interior:

─(osboxes㉿osboxes)-[~/Desktop/t-hoarder/keys]
└─$ ls
AAAAAAAAAAAAAAAAAAAAAKclxxx0.key
AppMr.XX.key
XXXXXX.key

Ahora el error es diferente y solo me da errores de autenticación relativos a las líneas del script tweet streaming large:

-->File output:  /home/osboxes/Desktop//t-hoarder/store/streaming_SabadoTest.txt
Error in oauth autentication, user key 
Traceback (most recent call last):
  File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 462, in <module>
    main()
  File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 440, in main
    oauth=oauth_keys(app_keys_file,user_keys_file)
  File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 54, in __init__
    print 'Error in oauth autentication, user key ', user_keys_file_num
NameError: global name 'user_keys_file_num' is not defined

Alguna idea de como autenticarme correctamente? Donde puede estar el error?

Gracias de antemano.

**Comment by MarcEngineer** [comment]
@congosto

**Comment by MarcEngineer** [comment]
@congosto
