### ISSUE TITLE
Error de autenticación del usuario

### ISSUE THREAD

**Issue by MarcEngineer** [congosto/t-hoarder#15]
La herramienta ejecuta los experimentos pero no genera los outputs esperados, no realiza una descarga de tweets ni consume los recursos de la API.

En un primer momento se estructuró el expermiento como aparece en la wiki, tras su ejecución, el archivo nohup.out establecía un error de no encontrar el archivo en la carpeta "keys" correspondiente al "bearer token" tal que así:

ohup: appending output to '/home/osboxes/nohup.out'

En el archivo aparece el siguiente error:

-->File output: /home/osboxes/Desktop//t-hoarder/store/streaming_SabadoTest.txt
Traceback (most recent call last):
File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 462, in
main()
File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 440, in main
oauth=oauth_keys(app_keys_file,user_keys_file)
File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 45, in init
f = open( self.user_keys_file, 'rU')
IOError: [Errno 2] No such file or directory: '/home/osboxes/Desktop//t-hoarder/keys/AAAAAAAAAAAAAAAAAAAAAKclWAEAAAAAmxxx.key'
run command python2.7 /home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py /home/osboxes/Desktop/ SabadoTest AppMr.XX.key AAAAAAAAAAAAAAAAAAAAAKclWAEAAAAAmpUtc7xxxDSkuZ0.key --words words.txt

Ya que veo que me solicita un archivo con el nombre del Bearer token, creo un txt con el nombre del Bearer token y lo incluyo en su interior:

─(osboxes㉿osboxes)-[~/Desktop/t-hoarder/keys]
└─$ ls
AAAAAAAAAAAAAAAAAAAAAKclxxx0.key
AppMr.XX.key
XXXXXX.key

Ahora el error es diferente y solo me da errores de autenticación relativos a las líneas del script tweet streaming large:

-->File output: /home/osboxes/Desktop//t-hoarder/store/streaming_SabadoTest.txt
Error in oauth autentication, user key
Traceback (most recent call last):
File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 462, in
main()
File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 440, in main
oauth=oauth_keys(app_keys_file,user_keys_file)
File "/home/osboxes/Desktop//t-hoarder/scripts/tweet_streaming_large.py", line 54, in init
print 'Error in oauth autentication, user key ', user_keys_file_num
NameError: global name 'user_keys_file_num' is not defined

Alguna idea de como autenticarme correctamente? Donde puede estar el error?

Gracias de antemano. @congosto

**Comment by congosto** [comment]
Supongo que para crear lo tokenes has seguido el procedimiento que se indica en lapara guardar los datos de tu app en el directorio keys  wiki https://github.com/congosto/t-hoarder/wiki/Crear-credenciales-para-acceder-a-la-API 

Supongo que ha creado un token de tu app con un usuario tuyo de twitter con la opción 1
https://github.com/congosto/t-hoarder/wiki/Instalaci%C3%B3n-y-arrancar-de-t-hoarder

¿Tuviste algún problema al hacerlo?

**Comment by congosto** [comment]
es un error del script,  al imprimir el error de autentificación en vez de user_keys_file_num,  debería poner user_keys_file.

El script se para porque le da un error en la autentificación porque las claves no están correctas

**Comment by congosto** [comment]
Si parece que has seguido los pasos.
No borres nada. será otro el problema
voy a arreglar el bug del script para que aparezca el nombre del fichero de claves que te da el problema

**Comment by congosto** [comment]
He subido una nueva versión corrigiendo el error. Ahora debería decirte el fichero de claves del usuario que da error.

**Comment by congosto** [comment]
La única duda es de cuando creaste la app. ¿lo hiciste en el portal de desarrolladores? 
Mis apps son anteriores al portal de desarrolladores y no sé si hay algún problema con las claves creadas como desarrollador porque la API es diferente

**Comment by MarcEngineer** [comment]
> La única duda es de cuando creaste la app. ¿lo hiciste en el portal de desarrolladores? Mis apps son anteriores al portal de desarrolladores y no sé si hay algún problema con las claves creadas como desarrollador porque la API es diferente

La App la cree desde la plataforma del portal de desarrolladores de twitter hace una semana en https://developer.twitter.com/en/apps

<img width="657" alt="image" src="https://user-images.githubusercontent.com/95224809/143905160-63d38f64-7c0f-40a7-9d9d-1efbb33cc3ea.png">


No se si puede ser algun problema relativo al "Bearer Token", probaré ahora con la versión actualizada, muchas gracias por su atención y agilidad en la respuesta. 
Conoce alguna forma de obtener esas claves sin necesidad de generarlas desde el portal de desarrollador?

**Comment by congosto** [comment]
¿Tomaste bien nota de la Consumer y Secret keys?

Hay que tener mucho cuidado al copiar pegar para que no se meta nungún carácter de control.
Hay que usar un editor de texto plano para hacerlo

![image](https://user-images.githubusercontent.com/306173/143912606-5c9f9898-d584-45c9-83e7-370e7926b21e.png)

**Comment by MarcEngineer** [comment]
La autenticación se realizó con éxito y me pidió el código de la web de developers para autenticar la cuenta por lo que entiendo que si introduje bien la consumer y la secret key. 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/95224809/143914262-d469e2e9-87e8-416d-9fe4-32dfbd55fdbb.png">


Adjunto ejemplo al respecto

**Comment by congosto** [comment]
La autenticación del la opción 1 puede ser correcta pero si los datos de las claves de la app son incorrectos, generar un token incorrecto. 

Creo que como funciona es que se les pasan las claves de la app y el usuario y Twitter calcula el token con esos datos. No estoy segura que Twitter compruebe que las claves que se le pasan sean correctas.

En algunos talleres que he dado los alumnos habían copiado mal la clave (copiarla en un fichero word, copiarla en un fichero de texto dejando espacios en blanco o tabulaciones) y le generaba el token sin error. Luego no funcionaba ese token para el resto de las operaciones

Comprueba que están bien copiada las claves al fichero

**Comment by congosto** [comment]
Creo que no debería dar problema, pero por favor,  pon un salto de línea después del consumer secret y vuelve a generar el token del usuario  con la opción 1

**Comment by MarcEngineer** [comment]
Tras diversas pruebas he conseguido solventar el problema de la autenticación,

Un primer intento donde utilizo la nueva versión y consigo conectar el experimento y recibo un error 401 (no consigo autenticarme a pesar de correr el experimetno)
<img width="702" alt="image" src="https://user-images.githubusercontent.com/95224809/143958354-60b92ccc-0973-44a7-b0e2-b258700faca7.png">

Tras esto pruebo a resetear las keys desde la plataforma developer de Twitter:

1. He reseteado las keys de la App de Twitter
2. Nueva generación de credenciales dentro del directorio Keys mediante el editor vi
3. Genero un nuevo proyecto de prueba
4. Recibo un error inesperado:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/95224809/143958498-8cd61370-0b5c-4b94-a93e-1f9da836b489.png">


ERROR 403 (una vez solventado el error de autenticación 401)  el servidor es contactado pero deniega mi petición. Entiendo que si el error ya no es el 401 es que la autenticación se ha realizado con éxito.

**Comment by congosto** [comment]
mmm

**Comment by congosto** [comment]
Si, parece que la autenticación ha pasado. 

Te dice que no tienes acceso al recurso.

Por favor, me podrías enseñar el command_start del experimento y el nohup

**Comment by MarcEngineer** [comment]
Disculpe el retraso, no tuve acceso en el día de ayer al recurso:
En lo relativo al nohup:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/95224809/144204125-8cc3bee0-36bf-4e11-b149-f457b6f48ba6.png">

En relación al command_start:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/95224809/144204574-c5ba026e-3906-4a8a-b534-c863a37047f1.png">


Parece que se está ejecutando de forma correcta.

**Comment by congosto** [comment]
¿Cuántos streaming tienes corriendo?

Tiene que tener un token de usuario por cada streaming
 Por favor, pásame el resultado de este comando

ps -e -o pid,args | grep streaming

**Comment by MarcEngineer** [comment]
porfin es el nombre del experimento
<img width="392" alt="image" src="https://user-images.githubusercontent.com/95224809/144211920-2b72c282-6c84-416b-acae-4f5738d03193.png">


en principio el streaming que está corriendo sería solo el respectivo al experimento "porfin"

**Comment by congosto** [comment]
Según esto debería recoger datos. Por favor, me puedes hacer  un ls del directorio store?

**Comment by MarcEngineer** [comment]
Adjunto el ls del directorio store:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/95224809/144213880-7e509fea-71c9-42fb-9e1b-8cf65d6e9828.png">

Adicionalmente incluyo un cat de los archivos que se han generado relacionados con el experimento en ejecución:

$cat streaming_porfin.log 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/95224809/144214130-f8518801-fc3f-453d-a7e7-0b3a41bf2f7c.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/95224809/144214337-cf7ba992-4061-46bc-b590-68375fe4ecaa.png">

**Comment by congosto** [comment]
Vale, no tiene datos.
El usuario con el que has hecho el token supongo que no está bloqueado.

Solo se me ocurre probar abrir un perfil nuevo y crear otro token con él con la opción 1 y lanzar un streaming con este nuevo usuario

**Comment by MarcEngineer** [comment]
Llegado a este punto entiendo que el problema ya no es de autenticación (error 401) sino de permisos a la API como comenta.
<img width="534" alt="image" src="https://user-images.githubusercontent.com/95224809/144236299-04965068-4e3f-49ff-897d-c43efd865bec.png">

La solicitud se comprende pero parece que mis permisos no son suficientes cosa incomprensible dado que tengo hasta 500.000 tweets para descarga con el plan "essential"
<img width="719" alt="image" src="https://user-images.githubusercontent.com/95224809/144236792-eea267fa-1b20-4426-9e49-66ab5cad2a30.png">

He probado a crear una nueva cuenta y he solicitado permisos adicionales con la anterior para ver si se trata de una incompatibilidad de mis permisos con las solicitudes. 

Hasta ahora, con la nueva cuenta y tokens, las solicitudes persisten con el mismo error (403)

<img width="541" alt="image" src="https://user-images.githubusercontent.com/95224809/144237068-775ef38b-17fe-4c45-ae06-6926bc03f868.png">

**Comment by MarcEngineer** [comment]
Cree que el error puede tener que ver con esto?
<img width="845" alt="image" src="https://user-images.githubusercontent.com/95224809/144238368-4d5eb320-ad1b-4aea-bdaa-6ca7f1744b19.png">

**Comment by congosto** [comment]
T_hoarder_kit accede a la API V1.1.
Puede que con la app de desarrolladores solo puedas acceder a a API V2. Como te comenté al principio mis APP son anteriores a la creación del portal de desarrolladores 
![image](https://user-images.githubusercontent.com/306173/144242331-b4496ff1-2cc6-4fae-97d0-4a4ef92c25e1.png)
.

https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api

**Comment by MarcEngineer** [comment]
Entonces creo que hemos detectado la fuente del error del 403, muchas gracias por ayudarme a solucionar el error de autenticación (401). 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/95224809/144250229-cd592325-dd7b-4d61-bb4f-0e9f4f47acd5.png">

Por si ayuda a otros, cuando se realiza el registro en el portal de desarrolladores, twitter te da acceso al modo "essential" que no tiene acceso a la api v.1 como se ve en la imagen.

**Comment by congosto** [comment]
Pide un pasar a la pantalla de elevated

**Comment by MarcEngineer** [comment]
Buenas tardes profesora, tras un par de intentos he conseguido pasar a la pantalla "elevated"

He probado a crear una nueva app normal desde cero e incluso a crear una app "standard alone" que solo contacta con la apiv1.1
<img width="559" alt="image" src="https://user-images.githubusercontent.com/95224809/145683680-b2ca3c05-ffb4-4d30-a8c4-69cba7422fb5.png">
<img width="472" alt="image" src="https://user-images.githubusercontent.com/95224809/145683703-7e8f2f21-f439-4270-a192-794b6e741eee.png">

El problema ahora redunda en que t-hoarder no me permite autenticarme devolviendome un error 401 habiendo probado cerca de 10 veces con diferentes opciones como acabo de comentar. 
He puesto las credenciales en un vi sin espacios y dejando saltos de línea linux
El error siempre es ahora el 401
<img width="463" alt="image" src="https://user-images.githubusercontent.com/95224809/145683613-50511d4d-3c1d-4c66-aeb4-301b630d9ae6.png">
